---
title: "Colorado COVID-19 Data Visualization"
author: "Group 2"
date: "12/14/2020"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---


```{r, include = FALSE}
library(flexdashboard)
library(readr)
library(lubridate)
library(shiny)
library(jsonlite)
library(maptools)
library(ggplot2)
library(tidyr)
library(dplyr)
library(purrr)
library(leaflet)
library(plotly)
library(DT)
library(ggthemes)
library(viridis)
library(flexdashboard)
library(readr)
library(lubridate)
library(shiny)
library(jsonlite)
library(maptools)
library(ggplot2)
library(tidyr)
library(dplyr)
library(purrr)
library(leaflet)
library(plotly)
library(DT)
library(ggthemes)
library(viridis)
library(tidyverse)
library(scales)
library(stringr)
library(sf)
library(tigris)
```

```{r, include = FALSE}
# Import Data
raw_data <- read.csv("../Desktop/STATS FINAL PROJECT/CDPHE_COVID19_County-Level_Open_Data_Repository.csv")
covid <- raw_data %>% 
  mutate(COUNTY = as.factor(COUNTY),
         Date = mdy(Date),
         Desc_ = as.factor(Desc_),
         FIPS = as.factor(FIPS),
         FULL_ = as.factor(FULL_),
         LABEL = as.factor(LABEL),
         Metric = as.factor(Metric),
         ObjectId = as.factor(ObjectId),
         POP = as.factor(POP),
         Rate = as.numeric(Rate),
         Value = as.numeric(Value)) %>% 
  rename(county = COUNTY,
         date = Date,
         descriptor = Desc_,
         fips = FIPS,
         full = FULL_,
         label = LABEL,
         metric = Metric,
         objectid = ObjectId,
         population = POP,
         rate = Rate,
         value = Value) %>% 
  select(label, fips, population, descriptor, metric, value, rate, date, objectid) %>% 
  mutate(response = coalesce(value, rate)) %>% 
  select(label, fips, population, metric, response, date)
```

Row
-------------------------------------
    
### Chart 1
    
```{r Data Cleaning 3, include = FALSE}
state_new_cases <- covid %>% 
  filter(metric %in% c("Cases")) %>% 
  group_by(date) %>% 
  summarize(state_cumulative_total_perday = sum(response)) %>% 
  ungroup() %>% 
  mutate(cases_perday = state_cumulative_total_perday - lag(state_cumulative_total_perday)) %>% 
  select(date, cases_perday)
#View(state_new_cases)

state_new_deaths <- covid %>% 
  filter(metric == "Deaths") %>% 
  group_by(date) %>% 
  summarize(state_cumulative_total_perday = sum(response)) %>% 
  ungroup() %>% 
  mutate(deaths_perday = state_cumulative_total_perday - lag(state_cumulative_total_perday)) %>% 
  select(date, deaths_perday)
#View(state_new_deaths)

state_new_full <- left_join(state_new_cases, state_new_deaths, by = "date")
#head(state_new_full)
```

```{r plot 3}
perday_plot <- na.omit(state_new_full) %>% 
  ggplot(aes(x = date)) +
  geom_col(aes(y = cases_perday), size = 1, fill = "lightseagreen", stat = "identity", bin = 30) +
  geom_line(aes(y = deaths_perday), size = 0.7, color = "lightsalmon") +
  labs(x = "", y = "") +
  scale_y_continuous(name = "Cases", labels = scales::comma) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  ggtitle("Colorado New Cases and Deaths", 
          subtitle = "per day") +
  theme_few()
# scale_colour_few("Light")
  
#perday_plot
ggplotly(perday_plot)
```
   
Row
-------------------------------------
    
### Chart 2
    
```{r clean, include = FALSE}
#Clean Data
tests <- covid %>% 
  filter(metric == "Cases") %>% 
  mutate(fips = str_pad(fips, 2, side = "left", pad = "0"),
         fips = str_pad(fips, 3, side = "left", pad = "0"),
         fips = paste0("08", fips)) %>% 
  select(fips,label, population, date, response) %>% 
  mutate(fips = as.factor(fips),
         response = as.numeric(response),
         population = as.character(population),
         label = as.character(label))
tests <- tests[with(tests, order(fips,date)),]
tests <- tests[cumsum(table(tests$fips)),]

##Geographic Data
colorado_counties <- counties(state = "CO", cb = TRUE, class = "sf")
#class(colorado_counties)
#class(colorado_counties$geometry)
#st_bbox(colorado_counties$geometry)

##Merge Geographic Data with Raw Data
co_county_events <- colorado_counties %>% 
  mutate(fips = paste(STATEFP, COUNTYFP, sep = "")) %>% 
  full_join(tests, by = "fips") %>% 
  mutate(n = response) %>% 
  mutate(n = ifelse(!is.na(n),n,0))

#Create pallet for Leaflet
bins <- c(0, 500, 5000, 15000, 25000, 50000, Inf)
pal <- colorBin("Set2", domain = co_county_events, bins = bins)
#Set2
##PLot data
```

```{r plot}
renderLeaflet({leaflet() %>% 
  addTiles() %>% 
#  fitBounds(-102.03,37,-109.03, 41) %>% 
#  fitBounds(-102.03,42,-109.03, 46) %>% 
  addPolygons(data = co_county_events,
              popup = ~ paste('<p>', "County:", label,'<p></p>',
                              '<p>', "Population:",population,'<p></p>',
                              '<p>', "Cases:", n),
              color = ~pal(n),
              weight = 2,
              opacity = 1,
              dashArray = "3",
              fillOpacity = 0.7,
              highlight = highlightOptions(
                weight = 2,
                color = "#667",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE),
              labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"),
                                          textsize = "15px",
                                          direction = "auto")) %>% 
  addLegend(data = co_county_events,
            title = "Cumulative number Cases",
            pal = pal, values = ~ n) %>% 
  addLayersControl(baseGroups = c("base map"),
                   overlayGroups = c("Cases","Deaths"))
})
```
    
### Chart 3

```{r, include = FALSE}
calendarHeat <- function(dates, 
                         values,
                         colors,
                         ncolors=99,
                         title,
                         date.form = "%Y-%m-%d", ...) {
  require(lattice, quietly = TRUE)
  require(grid, quietly = TRUE)
  
  if (class(dates) == "character" | class(dates) == "factor" ) {
    dates <- strptime(dates, date.form)
          }
  caldat <- data.frame(value = values, dates = dates)
  min.date <- as.Date(paste(format(min(dates), "%Y"),
                      "-1-1",sep = ""))
  max.date <- as.Date(paste(format(max(dates), "%Y"),
                       "-12-31", sep = ""))
  dates.f <- data.frame(date.seq = seq(min.date, max.date, by="days"))
  
  # Merge moves data by one day, avoid
  caldat <- data.frame(date.seq = seq(min.date, max.date, by="days"), value = NA)
  dates <- as.Date(dates) 
  caldat$value[match(dates, caldat$date.seq)] <- values
  
  caldat$dotw <- as.numeric(format(caldat$date.seq, "%w"))
  caldat$woty <- as.numeric(format(caldat$date.seq, "%U")) + 1
  caldat$yr <- as.factor(format(caldat$date.seq, "%Y"))
  caldat$month <- as.numeric(format(caldat$date.seq, "%m"))
  yrs <- as.character(unique(caldat$yr))
  d.loc <- as.numeric()                        
  for (m in min(yrs):max(yrs)) {
    d.subset <- which(caldat$yr == m)  
    sub.seq <- seq(1,length(d.subset))
    d.loc <- c(d.loc, sub.seq)
    }  
  caldat <- cbind(caldat, seq=d.loc)
  
  #color styles
  if (missing(colors)) colors <- c("#D61818", "#FFAE63", "#FFFFBD", "#B5E384")                          

  calendar.pal <- colorRampPalette(c(rgb(0,1,1,0), rgb(0,1,1,1)), alpha = TRUE)
  def.theme <- lattice.getOption("default.theme")
  cal.theme <-
     function() {  
    theme <-
    list(
      strip.background = list(col = "transparent"),
      strip.border = list(col = "transparent"),
      axis.line = list(col="transparent"),
      par.strip.text=list(cex=0.8))
      }
  lattice.options(default.theme = cal.theme)
  yrs <- (unique(caldat$yr))
  nyr <- length(yrs)
  print(cal.plot <- levelplot(value~woty*dotw | yr, data=caldat,
     as.table=TRUE,
     aspect=.12,
   layout = c(1, nyr%%7),
     between = list(x=0, y=c(0.5,0.5)),
     strip=TRUE,
     main = ifelse(missing(title), "", title),
     scales = list(
       x = list(
                 at= c(seq(2.9, 52, by=4.42)),
                 labels = month.abb,
                 alternating = c(1, rep(0, (nyr-1))),
                 tck=0,
                 cex = 0.7),
       y=list(
            at = c(0, 1, 2, 3, 4, 5, 6),
            labels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday",
                        "Friday", "Saturday"),
            alternating = 1,
            cex = 0.6,
            tck=0)),
     xlim =c(0.4, 54.6),
     ylim=c(6.6,-0.6),
     cuts= ncolors - 1,
     col.regions = (calendar.pal(ncolors)),
     xlab="" ,
     ylab="",
     colorkey= list(col = calendar.pal(ncolors), width = 0.6, height = 0.5),
     subscripts=TRUE
      ) )
  panel.locs <- trellis.currentLayout()
  for (row in 1:nrow(panel.locs)) {
      for (column in 1:ncol(panel.locs))  {
      if (panel.locs[row, column] > 0)
  {
      trellis.focus("panel", row = row, column = column,
                    highlight = FALSE)
  xyetc <- trellis.panelArgs()
  subs <- caldat[xyetc$subscripts,]
  dates.fsubs <- caldat[caldat$yr == unique(subs$yr),]
  y.start <- dates.fsubs$dotw[1]
  y.end   <- dates.fsubs$dotw[nrow(dates.fsubs)]
  dates.len <- nrow(dates.fsubs)
  adj.start <- dates.fsubs$woty[1]
  
  for (k in 0:6) {
   if (k < y.start) {
      x.start <- adj.start + 0.5
      } else {
      x.start <- adj.start - 0.5
        }
    if (k > y.end) {
       x.finis <- dates.fsubs$woty[nrow(dates.fsubs)] - 0.5
      } else {
       x.finis <- dates.fsubs$woty[nrow(dates.fsubs)] + 0.5
        }
      grid.lines(x = c(x.start, x.finis), y = c(k -0.5, k - 0.5), 
       default.units = "native", gp=gpar(col = "grey", lwd = 1))
       }
  if (adj.start <  2) {
   grid.lines(x = c( 0.5,  0.5), y = c(6.5, y.start-0.5), 
        default.units = "native", gp=gpar(col = "grey", lwd = 1))
   grid.lines(x = c(1.5, 1.5), y = c(6.5, -0.5), default.units = "native",
        gp=gpar(col = "grey", lwd = 1))
   grid.lines(x = c(x.finis, x.finis), 
        y = c(dates.fsubs$dotw[dates.len] -0.5, -0.5), default.units = "native",
        gp=gpar(col = "grey", lwd = 1))
   if (dates.fsubs$dotw[dates.len] != 6) {
   grid.lines(x = c(x.finis + 1, x.finis + 1), 
        y = c(dates.fsubs$dotw[dates.len] -0.5, -0.5), default.units = "native",
        gp=gpar(col = "grey", lwd = 1))
        }
   grid.lines(x = c(x.finis, x.finis), 
        y = c(dates.fsubs$dotw[dates.len] -0.5, -0.5), default.units = "native",
        gp=gpar(col = "grey", lwd = 1))
        }
  for (n in 1:51) {
    grid.lines(x = c(n + 1.5, n + 1.5), 
      y = c(-0.5, 6.5), default.units = "native", gp=gpar(col = "grey", lwd = 1))
          }
  x.start <- adj.start - 0.5
  
  if (y.start > 0) {
    grid.lines(x = c(x.start, x.start + 1),
      y = c(y.start - 0.5, y.start -  0.5), default.units = "native",
      gp=gpar(col = "black", lwd = 1.75))
    grid.lines(x = c(x.start + 1, x.start + 1),
      y = c(y.start - 0.5 , -0.5), default.units = "native",
      gp=gpar(col = "black", lwd = 1.75))
    grid.lines(x = c(x.start, x.start),
      y = c(y.start - 0.5, 6.5), default.units = "native",
      gp=gpar(col = "black", lwd = 1.75))
   if (y.end < 6  ) {
    grid.lines(x = c(x.start + 1, x.finis + 1),
     y = c(-0.5, -0.5), default.units = "native",
     gp=gpar(col = "black", lwd = 1.75))
    grid.lines(x = c(x.start, x.finis),
     y = c(6.5, 6.5), default.units = "native",
     gp=gpar(col = "black", lwd = 1.75))
     } else {
        grid.lines(x = c(x.start + 1, x.finis),
         y = c(-0.5, -0.5), default.units = "native",
         gp=gpar(col = "black", lwd = 1.75))
        grid.lines(x = c(x.start, x.finis),
         y = c(6.5, 6.5), default.units = "native",
         gp=gpar(col = "black", lwd = 1.75))
         }
         } else {
             grid.lines(x = c(x.start, x.start),
              y = c( - 0.5, 6.5), default.units = "native",
              gp=gpar(col = "black", lwd = 1.75))
             }
  
   if (y.start == 0 ) {
    if (y.end < 6  ) {
    grid.lines(x = c(x.start, x.finis + 1),
     y = c(-0.5, -0.5), default.units = "native",
     gp=gpar(col = "black", lwd = 1.75))
    grid.lines(x = c(x.start, x.finis),
     y = c(6.5, 6.5), default.units = "native",
     gp=gpar(col = "black", lwd = 1.75))
     } else {
        grid.lines(x = c(x.start + 1, x.finis),
         y = c(-0.5, -0.5), default.units = "native",
         gp=gpar(col = "black", lwd = 1.75))
        grid.lines(x = c(x.start, x.finis),
         y = c(6.5, 6.5), default.units = "native",
         gp=gpar(col = "black", lwd = 1.75))
         }
         }
  for (j in 1:12)  {
     last.month <- max(dates.fsubs$seq[dates.fsubs$month == j])
     x.last.m <- dates.fsubs$woty[last.month] + 0.5
     y.last.m <- dates.fsubs$dotw[last.month] + 0.5
     grid.lines(x = c(x.last.m, x.last.m), y = c(-0.5, y.last.m),
       default.units = "native", gp=gpar(col = "black", lwd = 1.75))
     if ((y.last.m) < 6) {
        grid.lines(x = c(x.last.m, x.last.m - 1), y = c(y.last.m, y.last.m),
         default.units = "native", gp=gpar(col = "black", lwd = 1.75))
       grid.lines(x = c(x.last.m - 1, x.last.m - 1), y = c(y.last.m, 6.5),
         default.units = "native", gp=gpar(col = "black", lwd = 1.75))
     } else {
        grid.lines(x = c(x.last.m, x.last.m), y = c(- 0.5, 6.5),
         default.units = "native", gp=gpar(col = "black", lwd = 1.75))
      }
   }
   }
   }
  trellis.unfocus()
  } 
  lattice.options(default.theme = def.theme)
}
covid_data <- covid %>% 
  filter(metric == "Total Tests Performed") %>% 
  group_by(date) %>% 
  summarize(cumulative_test_state_perday = sum(response)) %>% 
  mutate(test_perday = cumulative_test_state_perday - lag(cumulative_test_state_perday)) %>% 
  select(date, test_perday)

```

```{r}
cal_map <- calendarHeat(covid_data$date, covid_data$test_perday, ncolors = 99, varname ="COVID CASES", date.form = "May")
cal_map
```

